configuration dir replaces file

diff --git a/backup-reporter b/backup-reporter
--- a/backup-reporter
+++ b/backup-reporter
@@ -4,7 +4,7 @@
 # SECTION: Script global variables
 me=$(basename $0)
 verbosity=2 # Start counting at 2 so that any increase to this will result in a minimum of file descriptor 3.
-maxverbosity=5 # The highest verbosity we use / allow to be displayed.
+maxverbosity=3 # The highest verbosity we use / allow to be displayed.
 
 # SECTION: Dependencies
 dependencies=("echo" "bash" "tr")
@@ -15,7 +15,7 @@ done
 # SECTION: Help function
 function_Help() {
 	cat <<-EOH >&2
-	Usage: $me [OPTION]... [FILE]
+	Usage: $me [OPTION]... [DIR]
 	Description text. ###WIP
 	Example: $me -s <ORGANIZATION>
 	Options:
@@ -23,7 +23,7 @@ function_Help() {
 	   -n                         Add new monitored backup
 	   -s <ORGANIZATION>          Scan <ORGANIZATION> for recent backups
 
-	With no FILE, /etc/$me.conf is used.
+	With no DIR, /etc/$me.d/ is used.
 	EOH
 	###printf '%5s\t\t%s' "-s" "Scan"
 }
@@ -53,11 +53,16 @@ done
 
 printf "%s %d\n" "Verbosity level set to:" "$verbosity" >&3
 
-if [[ ! -z "$1" ]]; then # If config file is specified
-	if [[ ! -f "$1" ]]; then # If is not file, error and quit
-		printf "%s: %s %s\n" "$me" "Configuration file not found:" "$1" >&2
+if [[ ! -z "$1" ]]; then # If config directory is specified
+	if [[ ! -d "$1" ]]; then # If is not directory, error and quit
+		printf "%s: %s %s\n" "$me" "Configuration path not found:" "$1" >&2
 		exit 1;
 	fi
 fi
 
-printf "%s: %s %s\n" "$me" "Using configuration file" "${1-/etc/$me.conf}" >&3
+printf "%s: %s %s\n" "$me" "Using configuration path" "${1-/etc/$me.d/}" >&3
+
+# SECTION: Scan function
+function_Scan(organization){
+
+}
